### ISSUE TITLE
Pubspec Assist: An error has occurred when searching Dart pub.

### ISSUE THREAD

**Issue by gendseo** [jeroen-meijer/pubspec-assist#1]
Flutter Version
dev 0.96

Error problem
Pubspec Assist: An error has occurred when searching Dart pub.

**Comment by jeroen-meijer** [comment]
Thanks for your issue report.

Pubspec Assist could probably use a better error reporting system...
I'll push an update ASAP that saves a log of some sort so I can look into your issue a bit better.

On my end everything works fine.
In the meantime, please make sure the plugin and VS Code are up to date.

**Comment by jeroen-meijer** [comment]
@gendseo I've just pushed an update to Pubspec Assist that includes better error reporting. Please try recreating your issue and add the additional information you get by pushing 'Report issue'.

**Comment by gendseo** [comment]
@jeroen-meijer okay.I tried to use the Pubspec Assis install flutter plugin on morning, It did not report any errors to me.I will pay attention to this issue.

**Comment by jeroen-meijer** [comment]
Thank you for checking it again. I'll close this issue. Feel free to open a new one if any errors occur.
