### ISSUE TITLE
Add a settings to confirm what the user actually meant

### ISSUE THREAD

**Issue by Cyberavater** [jeroen-meijer/pubspec-assist#111]
Currently, if I type bloc, it adds bloc. But what I would like is that it would ask me if I want to install bloc or flutter_bloc like it does when I type 'blo'. This behavior could be enabled via a setting.

**Comment by jeroen-meijer** [comment]
Hi there,

This is already implemented 😄 
You can set this setting to `false` and you'll get the behavior you want 👍🏻 

Let me know if this worked for you! 👋🏻 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/14292245/140299850-df2230c4-4759-4353-bbb7-8b22f43a3dac.png">
