### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by james-sebastian** [jeroen-meijer/pubspec-assist#13]
- Issue Type: `Performance`
- Extension Name: `pubspec-assist`
- Extension Version: `0.3.6`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/james/jeroen-meijer.pubspec-assist-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for submitting the report.

However, it seems you have not actually attached the file, but rather only the path to it. Therefore, it's hard for me to identify the problem that may have caused the high CPU load. Please attach the file and reopen the issue.
