### ISSUE TITLE
Bug when installing package with almost similar name

### ISSUE THREAD

**Issue by skybur** [jeroen-meijer/pubspec-assist#2]
Hi there, thanks for developing this extension.
I encountered a bug when trying to install a package.
My pubspec.yaml contains `shared_preferences` package. When I tried to install `share` package, the extension replaced the `shared_preferences` with the `share`.

**Comment by jeroen-meijer** [comment]
Hey there @skybur

Sorry for my late response; I'm currently on holidays.

Thanks for your big report. I'm aware of issues like these and your use case will be helpful in fixing them.
When an update is released, I'll tell you in here.

Thanks again.

**Comment by jeroen-meijer** [comment]
@skybur The issue should be fixed now. Thanks for your help!
