### ISSUE TITLE
Bug Report: Rest client error: Error: connect ECONNREFUSED 192.168.1.16:808

### ISSUE THREAD

**Issue by c26ranto** [jeroen-meijer/pubspec-assist#21]
This error seems to be caused by my laptop which is behind the proxy, maybe you can fix this out.

**Comment by jeroen-meijer** [comment]
Hi there,

Unfortunately I don’t know anything about this error. Please either add more context and information about the problem in your issue, or close it.

Thank you.

Regards.

**Comment by jeroen-meijer** [comment]
Not enough information provided.

Closing. Feel free to reopen.

**Comment by carloswm85** [comment]
@jeroen-meijer is there any proxy settings available? I'm behind a proxy, and I get the following error when trying to add a dependency,

![image](https://github.com/jeroen-meijer/pubspec-assist/assets/29048235/bcb41a15-8f56-422e-90a7-d3af7a2b33e6)

Let me know if I should take this to another new issue. Let me know if you need more information. For the most part this is everything I have. 

VSCode goes through the proxy freely.
