### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chinkysight** [jeroen-meijer/pubspec-assist#27]
- Issue Type: `Performance`- Extension Name: `pubspec-assist`- Extension Version: `0.3.6`- OS Version: `Linux x64 5.3.0-26-generic`- VSCode version: `1.41.1`:warning: Make sure to **attach** this file from your *home*-directory::warning:`/home/chinkysight/jeroen-meijer.pubspec-assist-unresponsive.cpuprofile.txt`Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for opening this issue.

In order for me to help you, please do as your error says.
> Make sure to attach this file from your home-directory:⚠️`/home/chinkysight/jeroen-meijer.pubspec-assist-unresponsive.cpuprofile.txt`

Thanks.

Best regards.
