### ISSUE TITLE
Search updates

### ISSUE THREAD

**Issue by blondie63** [jeroen-meijer/pubspec-assist#31]
I'm using Pubspec to see dependencies must to be updates and it working but not all updates are listed.. i see that this extension is 2 years old, dead project ?

**Comment by jeroen-meijer** [comment]
I understand your thoughts.
The project is not entirely dead, just on low-maintenance.
Because of multiple factors (mostly time-constraints), I don't have the time to implement new features as long as the current version functions well (which it does in my opinion).

As far as your first question goes ("I'm using Pubspec to see dependencies must to be updates and it working but not all updates are listed"), I'm not entirely sure what you mean. Could you clarify?

**Comment by blondie63** [comment]
Look the attache screenshots
On my test prj i've flutter_i18n: ^0.10.1 and pubspec show this version white colored so i understand that there's no new version (pubspec1) , but really there's a new version.. 0.13.0 (pubspec2)

<img width="798" alt="pubspec1" src="https://user-images.githubusercontent.com/1261851/77935869-5724dc00-72b2-11ea-9156-223eedbf1336.png">
<img width="779" alt="pubspec2" src="https://user-images.githubusercontent.com/1261851/77935874-58560900-72b2-11ea-82fc-bf2f47488d5e.png">

What do you think ?

**Comment by jeroen-meijer** [comment]
That plugin you're showing is not Pubspec Assist (my plugin).
Let me know if this issue is still relevant.

As far as version management goes for Pubspec Assist, it takes the latest version directly from https://pub.dev/, so I don't see a way for it to miss a version.

**Comment by blondie63** [comment]
Sorry for mistake, really i've installed your extension and others with similar name..
I've never used your because i don't understand how to use it..
There's no icon to invoke, only a keyboard shortcut?

**Comment by jeroen-meijer** [comment]
That's right, you use the Command Palette (`⌘+Shift+P` or `Ctrl+Shift+P`) and search for `Pubspec Assist`. You'll see an option to add a dependency. If a package is already in the list of dependencies, it will be updated to the latest version.

![Gif preview](https://camo.githubusercontent.com/650e4f170cf205ea3412371ea241c720b656782a/68747470733a2f2f692e696d6775722e636f6d2f5732634775504c2e676966)

Hope that helps.

Closing this.

**Comment by blondie63** [comment]
Thanks !
