### ISSUE TITLE
Bug Report: Rest client error: Error:     No response from Pub API call.    Search type: \PACKAGE\.    Details: \Package name: dart:convert\.

### ISSUE THREAD

**Issue by Appholeex** [jeroen-meijer/pubspec-assist#32]
whenever i try to add the dart:convert dependency in pubspec.ymal it give me an error

Pubspec Assist: A critical error has occurred. If this happens again, please report it. Error message: Rest client error: Error: No response from Pub API call. Search type: "PACKAGE". Details: "Package name: dart:convert".

**Comment by jeroen-meijer** [comment]
Hi there,

You should not add `dart:...` packages as dependencies. They are already included in the Dart language, so you can import them immediately.

Best regards.
