### ISSUE TITLE
Text misplaced

### ISSUE THREAD

**Issue by CodeDoctorDE** [jeroen-meijer/pubspec-assist#34]
![image](https://user-images.githubusercontent.com/20452814/81311446-b03c1880-9085-11ea-85da-36b5a3cdbb1a.png)
The version text is misplaced!

**Comment by jeroen-meijer** [comment]
Hi there,

From the screenshot and the description you provided, I don't understand what issue you're having. Please describe your problem in more detail and provide steps to reproduce it.

Thank you.

**Comment by CodeDoctorDE** [comment]
the texts are missplaced. look on the version name

**Comment by jeroen-meijer** [comment]
I'm still not sure what you're talking about.
Do you mean something's wrong with the version numbers in green? If so, they look right to me.

Just to make sure - the line above every dependency saying `Satisfies x.x.x+x` does not come from Pubspec Assist, but from another VS Code extension.

**Comment by CodeDoctorDE** [comment]
The text Satisfies ß.4.0+17 should be above package_info and not above the empty line

**Comment by jeroen-meijer** [comment]
Thanks for the clarification.

Again, that's not this plugin, Pubspec Assist.

The extension you're talking about is probably [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens).
Please make a descriptive bug report at their GitHub repository.

Closing.

**Comment by CodeDoctorDE** [comment]
Oh thanks :D
