### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BalanaguYashwanth** [jeroen-meijer/pubspec-assist#35]
- Issue Type: `Bug`
- Extension Name: `pubspec-assist`
- Extension Version: `1.0.3`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.45.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jeroen-meijer** [comment]
Hi there,

From the description you provided, I don't understand what issue you're having. Please describe your problem in more detail and provide steps to reproduce it. (And paste the data from your clipboard like your issue says.)

Thank you.
