### ISSUE TITLE
Docs don't seem to show how to use it. :)

### ISSUE THREAD

**Issue by jaggzh** [jeroen-meijer/pubspec-assist#36]
Beautiful docs and animation -- but perhaps we could add something that says how to get to the package search field?  I'm probably missing it somewhere, in which case, perhaps we can make it more clear?  If it's the command-palette (ctrl-shift-p), then maybe the extension isn't working for me -- I type "video" there (to get the video_player dependency/version added), and there's no item matching).

**Comment by Flashee** [comment]
I'm having the same issue.  I cannot find the keybind that is used for searching.  I also cannot not even find out where I can change the keybind.

**Comment by jeroen-meijer** [comment]
Great point, both of you.

I added usage instructions in the latest version (v2.0.0).
Thanks for the suggestion! 😄

Closing this.
