### ISSUE TITLE
Enable to add pubs to dev_dependencies section

### ISSUE THREAD

**Issue by hashemp206** [jeroen-meijer/pubspec-assist#37]
Sometimes we need to add some pubs specific for development. currently I don't see any option for this, and we should do it manually.

like:
```
dev_dependencies:
  lint: ^1.2.0
```

**Comment by hashemp206** [comment]
it seems there is already there😁:
<img width="609" alt="Screen Shot 2020-06-11 at 7 08 36 AM" src="https://user-images.githubusercontent.com/3206748/84338744-1f8bb780-abb2-11ea-8822-e283543ad664.png">

**Comment by jeroen-meijer** [comment]
Haha, yep! 👍🏻
