### ISSUE TITLE
Bug Report: Expected YAML collection at dev_dependencies. Remaining path: firebase_auth

### ISSUE THREAD

**Issue by ernestsheldon** [jeroen-meijer/pubspec-assist#47]
Trying to use pub spec assist and getting this error after choosing the suggested dependency.

**Comment by jeroen-meijer** [comment]
Hi,

Thanks for opening the issue.
Please provide an example of your `pubspec.yaml` file and reproduction steps in detail.

Thanks.

**Comment by jeroen-meijer** [comment]
Fixed in 2.1.0.

Thank again!
