### ISSUE TITLE
Pubspec Assist: Pubspec file not found in workspace root. Open the pubspec file you would like to edit and try again.

### ISSUE THREAD

**Issue by puniohd** [jeroen-meijer/pubspec-assist#52]
How do i solve this problem? 

Pubspec Assist: Pubspec file not found in workspace root. Open the pubspec file you would like to edit and try again.

Visual Studio Code

**Comment by jeroen-meijer** [comment]
Hi there,

Easiest thing is to do as it says. Either open a project where the pubspec file is at the root, or open the file in the editor and then start Pubspec Assist.

Hope this was helpful enough. Feel free to reopen if you have any more questions.

Closing.
