### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Qotb912** [jeroen-meijer/pubspec-assist#53]
- Issue Type: `Bug`
- Extension Name: `pubspec-assist`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT ia32 10.0.19041`
- VSCode version: `1.47.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jeroen-meijer** [comment]
Hi, please open a new issue with more info and steps to reproduce.

Thanks. Closing this.
