### ISSUE TITLE
Critical error when dev_dependencies is null

### ISSUE THREAD

**Issue by JCKodel** [jeroen-meijer/pubspec-assist#54]
New flutter template sets `dev_dependencies` with `null`:

```yaml
dev_dependencies: null
```

This triggers a critical error while trying to add a dev dependency.

(yes, I'm aware that removing the `null` workarounds it, but #workaround-is-not-fix #fix-lives-matter)

**Comment by jeroen-meijer** [comment]
Hey there,

Thanks for the heads up. I'll have a look at this soon!

**Comment by jeroen-meijer** [comment]
Fixed in 2.1.0.

Thank again!
