### ISSUE TITLE
Bug Report: Expected YAML collection at dependencies. Remaining path: meta

### ISSUE THREAD

**Issue by cverdes** [jeroen-meijer/pubspec-assist#56]
Hello,

I was following the steps of the BLoC tutorial found at [this page](https://bloclibrary.dev/#/flutterlogintutorial) using only the VSCode extensions. 

At the moment I tried to add the `meta` dependency with the `>Pubspec Assist: Add/Update dependency` command, this error was raised:

![image](https://user-images.githubusercontent.com/6440942/94430572-8685aa00-016a-11eb-925f-51fefe292be4.png)

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for reporting it. Seems like it's related to some other issues related to adding dependencies to an (almost) empty pubspec. This should be fixed in the next version.

I'll keep you posted.
Thanks!

**Comment by jeroen-meijer** [comment]
Fixed in 2.1.0.

Thank again!

**Comment by LeonDWong** [comment]
@jeroen-meijer There is still 2.0.0 bug version in vs code plugin marketplace,  could you please update the latest version? New coming user is getting the issue otherwise.😂
