### ISSUE TITLE
Bug Report: implicit any dependencies are turned to 'null' when adding a package

### ISSUE THREAD

**Issue by lukepighetti** [jeroen-meijer/pubspec-assist#76]
If you have a dependency with implicit any (blank) and use `pubspec-assist`, it will turn the blank value into `null`. It should leave it blank.

```
  geojson: ^0.9.1
  intl: 
  permission_handler: ^5.0.1+1
```

```
  geojson: ^0.9.9
  intl: null
  permission_handler: ^5.0.1+1
```

**Comment by jeroen-meijer** [comment]
Thanks for the report, and apologies it has taken a while for me to get to this. It has been fixed in v2.3.2 (PR #139) 😄 

Closing this! 👋🏻
