### ISSUE TITLE
Removes newline from the end of pubspec.yaml

### ISSUE THREAD

**Issue by apaatsio** [jeroen-meijer/pubspec-assist#8]
The plugin doesn't respect a newline at the end of `pubspec.yaml` but removes it when user adds a new dependency.

To reproduce:

1. Open pubspec.yaml
2. Edit it so that there is a newline at the end.
3. Save
4. Run `Pubspec Assist: Add dependency` via Command Palette.
5. Add any package, e.g. `cloud_firestore`

Expected result: There's a newline at the end of pubspec.yaml

Actual result: There is no newline at the end of pubspec.yaml

**Comment by jeroen-meijer** [comment]
Thanks for the issue report.

This should be an easy fix. Except an update in the coming days.

**Comment by jeroen-meijer** [comment]
I've discovered that this depends on the formatter you're using.
I've added an exception to it anyway, so it will check for a newline and add it back if it was there before formatting the document.
Thanks for the heads up again.
Closing.
